export enum SessionType {
  WAITING = "WAITING",
  PRACTICE = "PRACTICE",
  QUALIFY = "QUALIFY",
  WARMUP = "WARMUP",
  QUALIFYHEAT = "QUALIFYHEAT",
  SECONDCHANCEHEAT = "SECONDCHANCEHEAT",
  PREFINAL = "PREFINAL",
  FINAL = "FINAL",
}
