export enum SessionState {
  NONE = "--",
  WARMUPLAP = "WARMUPLAP",
  PRESTART = "PRESTART",
  ROLLINGSTART = "ROLLINGSTART",
  STARTSEQUENCE = "STARTSEQUENCE",
  INPROGRESS = "INPROGRESS",
  RACEOVER = "RACEOVER",
  COMPLETE = "COMPLETE",
}
