export enum DriverStatusReason {
  NONE = "--",
  JUMPSTART = "JUMPSTART",
  TOOMANYOFFENCES = "TOOMANYOFFENCES",
  ROLLINGSTARTSPEEDING = "ROLLINGSTARTSPEEDING",
  ROLLINGSTARTTOOSLOW = "ROLLINGSTARTTOOSLOW",
  ROLLINGSTARTCORRIDOR = "ROLLINGSTARTCORRIDOR",
  ROLLINGSTARTOVERTAKE = "ROLLINGSTARTOVERTAKE",
  DIRECTOR = "DIRECTOR",
}
