export enum PenaltyOffence {
  NONE = "--",
  JUMPSTART = "JUMPSTART",
  CUTTING = "CUTTING",
  ROLLINGSTARTSPEEDING = "ROLLINGSTARTSPEEDING",
  ROLLINGSTARTTOOSLOW = "ROLLINGSTARTTOOSLOW",
  ROLLINGSTARTCORRIDOR = "ROLLINGSTARTCORRIDOR",
  ROLLINGSTARTOVERTAKE = "ROLLINGSTARTOVERTAKE",
}
