name: Release

on:
  release:
    types: [published]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [20]
        steps:
        - uses: actions/checkout@v4
        
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 9

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: 'https://registry.npmjs.org'
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install

        - run: pnpm publish --provenance --access public --no-git-checks
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  id-token: write
  contents: read